Vagrant.configure("2") do |config|
  config.vm.box = "artemnovak/ubuntu18.04"
  config.vm.box_version = "0.0.1"
  config.vm.hostname = 'ub18'
  config.vm.define 'Ubuntu 18.04'

  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.network "public_network", type: "dhcp"

  config.vm.synced_folder ".", "/home/vagrate/share", create: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'ubuntu18.04'
    vb.cpus = 2
    vb.memory = "4096"
  end

  config.vm.post_up_message = '------------------- Machine is ready! Please "vagrant ssh" to get in!. -------------------'
  
end
