Vagrant.configure("2") do |config| 
  config.vm.box = 'artemnovak/centos7-jenkins'
  config.vm.hostname = 'jenkins'
  config.vm.define 'jenkins-centos7'
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'jenkins'
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.post_up_message = '------------------- Machine is ready! Please "vagrant ssh" to get in!. -------------------'
  
end
